### ISSUE TITLE
开发环境会开启很多node进程，请问每次结束node服务 会结束对应的node进程吗

### ISSUE THREAD

**Issue by dylan-farm** [tjx666/react-typescript-boilerplate#3]

**Comment by dylan-farm** [comment]
fix: scripts/start.ts

`const sigs: Array<any> = ['SIGINT', 'SIGTERM'];
    sigs.forEach(sig => {
        // 我们监听了 node 信号，所以使用 cross-env-shell 而不是 cross-env
        process.on(sig, () => {
            // 先关闭 devServer
            httpServer.close();
            // 关掉node进程
            process.exit();
            // 在 ctrl + c 的时候随机输出 'See you again' 和 'Goodbye'
            console.log(
                chalk.greenBright.bold(`\n${Math.random() > 0.5 ? 'See you again' : 'Goodbye'}!`),
            );
        });
    });`

原本的脚本 每次Ctrol+C时没有退出 node 进程，每次重启时会重新启动新的node进程，所以会导致开发时间长了 后台有好多node进程导致内存不够。

**Comment by tjx666** [comment]
再过几天重点优化这个项目

**Comment by tjx666** [comment]
已修复
