### ISSUE TITLE
结束node服务后，修改文件还会继续进行编译

### ISSUE THREAD

**Issue by dylan-farm** [tjx666/react-typescript-boilerplate#4]

**Comment by dylan-farm** [comment]
这个问题 也是由于node进程没有结束导致的，参考上个issue的fix方法就可以了

**Comment by tjx666** [comment]
已修复 https://github.com/tjx666/react-typescript-boilerplate/commit/e12e44ed061241b87dbacb5c9f51c311ffc5d541

**Comment by tjx666** [comment]
已修复 https://github.com/tjx666/react-typescript-boilerplate/commit/e12e44ed061241b87dbacb5c9f51c311ffc5d541
