### ISSUE TITLE
打包之后没有声明文件

### ISSUE THREAD

**Issue by LaamGinghong** [tjx666/react-typescript-boilerplate#5]
即使tsconfig.json添加了`"declaration": true`，打包出来之后仍然没有声明文件

**Comment by LaamGinghong** [comment]
似乎是因为ts-loader中的`transpileOnly:true`的原因，但是fork-ts-checker-webpack-plugin里面没有找到开启生成.d文件的参数

**Comment by tjx666** [comment]
你为什么需要声明文件啊？前端项目是使用 babel 插件 [@babel/plugin-transform-typescript](https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options) 编译的

**Comment by LaamGinghong** [comment]
我的是组件库

**Comment by LaamGinghong** [comment]
> 你为什么需要声明文件啊？前端项目是使用 babel 插件 [@babel/plugin-transform-typescript](https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options) 编译的

**Comment by tjx666** [comment]
[相关 issues](https://github.com/babel/babel/issues?q=is%3Aissue+generate+typescript+declaration+file+is%3Aclosed )
