### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by pigeon-crypto** [tjx666/react-typescript-boilerplate#6]
移除yarn.lock之后重新yarn 安装，然后yarn start之后跑不成功。如图：
![image](https://user-images.githubusercontent.com/63844697/79561629-3d6dfc00-80dc-11ea-92fc-a7aac87987a5.png)
![image](https://user-images.githubusercontent.com/63844697/79561671-4ced4500-80dc-11ea-8766-48731787e3a6.png)

**Comment by tjx666** [comment]
那是因为 @types/webpack-hot-middleware 更新之后没有 Options 属性，模板最新代码已经修复这个问题了，你把代码同步到模板最新代码即可。
